# 使用 kitty 原生功能，不再自动启动 tmux
# launch zsh -c "tmux attach|| tmux"
# launch zsh -c "tmux new\; tmux choose-session"
# launch tmux attach\; choose-session
# launch tmux new
# launch zsh -c "tmux new"
launch zsh
